nuitka mole.py ^
--standalone --windows-console-mode=disable --jobs=8 --lto=yes --remove-output ^
--enable-plugin=pyside6 ^
--windows-icon-from-ico=icon.ico ^
--include-data-files=hook.dll=hook.dll ^
--file-description=摩尔抓包工具 ^
--product-name=摩尔抓包工具 ^
--copyright="Copyright (C) 2025 lingcraft. All Rights Reserved" ^
--file-version=1.0 ^
--product-version=1.0 ^
--onefile ^
--output-filename=摩尔抓包.exe ^
--output-dir="D:\Downloads"