[project]
name = "mole"
version = "1.12.5"
description = """
- 新增：新增显示官服不存在但平行服存在的衣服、坐骑等资源（官服请求的 swf 或 xml 资源不存在时改为请求平行服相应资源，并缓存到 %appdata%/mole/resource 目录下，加快加载速度）
"""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cffi~=2.1.1",
    "loguru~=0.7.3",
    "nuitka~=4.1.3",
    "packaging~=26.3",
    "py3amf~=0.9.1",
    "pypinyin~=0.55.0",
    "pyside6~=6.11.1",
    "requests~=2.34.2",
    "zstandard~=0.25",
]
