[project]
name = "mole"
version = "1.11.9"
description = """
- 新增：BridgeDLL.swf 增加 switchMapLogic 切换地图类的反射
- 优化：进入餐厅改为调用游戏内 switchMapLogic 的 switchMapLogicHandler 方法，避免通过发包方式多次进入后会卡顿的问题
- 优化：enter_map() 方法增加 map_type 参数，更加灵活调用，同时增加 switch_map() 方法，调用游戏内 switchMapLogicHandler 方法
- 优化：待升级魔灵下拉框增加宽度，显示信息更全
"""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cffi~=2.1.0",
    "loguru~=0.7.3",
    "nuitka~=4.1.3",
    "packaging~=26.2",
    "py3amf~=0.9.1",
    "pypinyin~=0.55.0",
    "pyside6~=6.11.1",
    "requests~=2.34.2",
    "zstandard~=0.25",
]
