# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtAxContainer import QAxWidget
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QHeaderView, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QPushButton, QSizePolicy, QTabWidget,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1480, 580)
        MainWindow.setMinimumSize(QSize(1480, 580))
        MainWindow.setMaximumSize(QSize(1480, 580))
        self.versionAction1 = QAction(MainWindow)
        self.versionAction1.setObjectName(u"versionAction1")
        self.versionAction1.setCheckable(True)
        self.versionAction1.setChecked(True)
        self.versionAction2 = QAction(MainWindow)
        self.versionAction2.setObjectName(u"versionAction2")
        self.versionAction2.setCheckable(True)
        self.versionAction3 = QAction(MainWindow)
        self.versionAction3.setObjectName(u"versionAction3")
        self.versionAction3.setCheckable(True)
        self.versionAction4 = QAction(MainWindow)
        self.versionAction4.setObjectName(u"versionAction4")
        self.versionAction4.setCheckable(True)
        self.versionAction5 = QAction(MainWindow)
        self.versionAction5.setObjectName(u"versionAction5")
        self.versionAction5.setCheckable(True)
        self.versionAction6 = QAction(MainWindow)
        self.versionAction6.setObjectName(u"versionAction6")
        self.versionAction6.setCheckable(True)
        self.versionAction7 = QAction(MainWindow)
        self.versionAction7.setObjectName(u"versionAction7")
        self.versionAction7.setCheckable(True)
        self.nodeAction1 = QAction(MainWindow)
        self.nodeAction1.setObjectName(u"nodeAction1")
        self.nodeAction1.setCheckable(True)
        self.nodeAction1.setChecked(True)
        self.nodeAction2 = QAction(MainWindow)
        self.nodeAction2.setObjectName(u"nodeAction2")
        self.nodeAction2.setCheckable(True)
        self.nodeAction2.setEnabled(False)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.groupBox = QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(970, 10, 501, 390))
        self.tableWidget = QTableWidget(self.groupBox)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 0, 501, 260))
        self.tableWidget.setMinimumSize(QSize(500, 0))
        self.textEdit = QPlainTextEdit(self.groupBox)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 290, 501, 100))
        self.sendClearButton = QPushButton(self.groupBox)
        self.sendClearButton.setObjectName(u"sendClearButton")
        self.sendClearButton.setGeometry(QRect(446, 360, 50, 25))
        self.sendLoopButton = QPushButton(self.groupBox)
        self.sendLoopButton.setObjectName(u"sendLoopButton")
        self.sendLoopButton.setGeometry(QRect(373, 360, 70, 25))
        self.recvCheckBox = QCheckBox(self.groupBox)
        self.recvCheckBox.setObjectName(u"recvCheckBox")
        self.recvCheckBox.setGeometry(QRect(86, 265, 80, 20))
        self.recvCheckBox.setChecked(True)
        self.sendButton = QPushButton(self.groupBox)
        self.sendButton.setObjectName(u"sendButton")
        self.sendButton.setGeometry(QRect(320, 360, 50, 25))
        self.sendCheckBox = QCheckBox(self.groupBox)
        self.sendCheckBox.setObjectName(u"sendCheckBox")
        self.sendCheckBox.setGeometry(QRect(6, 265, 80, 20))
        self.sendCheckBox.setChecked(True)
        self.clearButton = QPushButton(self.groupBox)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setGeometry(QRect(162, 262, 61, 26))
        self.extraButton = QPushButton(self.groupBox)
        self.extraButton.setObjectName(u"extraButton")
        self.extraButton.setGeometry(QRect(224, 262, 61, 26))
        self.axWidget = QAxWidget(self.centralWidget)
        self.axWidget.setControl(u"{d27cdb6e-ae6d-11cf-96b8-444553540000}")
        self.axWidget.setObjectName(u"axWidget")
        self.axWidget.setProperty(u"geometry", QRect(0, 0, 960, 560))
        self.tabWidget = QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(970, 402, 500, 148))
        self.tabWidget.setStyleSheet(u"QTabWidget::pane {\n"
"    background-color: #F0F0F0;\n"
"	border: 1px solid #DCDCDC;\n"
"}")
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.groupBox3 = QGroupBox(self.tab1)
        self.groupBox3.setObjectName(u"groupBox3")
        self.groupBox3.setGeometry(QRect(110, 64, 190, 61))
        self.ysqsFightButton = QPushButton(self.groupBox3)
        self.ysqsFightButton.setObjectName(u"ysqsFightButton")
        self.ysqsFightButton.setEnabled(False)
        self.ysqsFightButton.setGeometry(QRect(100, 20, 80, 31))
        self.ysqsLevelBox = QComboBox(self.groupBox3)
        self.ysqsLevelBox.addItem("")
        self.ysqsLevelBox.addItem("")
        self.ysqsLevelBox.addItem("")
        self.ysqsLevelBox.setObjectName(u"ysqsLevelBox")
        self.ysqsLevelBox.setEnabled(False)
        self.ysqsLevelBox.setGeometry(QRect(10, 23, 80, 25))
        self.ysqsLevelBox.setDuplicatesEnabled(False)
        self.groupBox1 = QGroupBox(self.tab1)
        self.groupBox1.setObjectName(u"groupBox1")
        self.groupBox1.setGeometry(QRect(-1, 2, 500, 61))
        self.mmgPVPButton = QPushButton(self.groupBox1)
        self.mmgPVPButton.setObjectName(u"mmgPVPButton")
        self.mmgPVPButton.setEnabled(False)
        self.mmgPVPButton.setGeometry(QRect(400, 20, 90, 31))
        self.mmgPVBButton = QPushButton(self.groupBox1)
        self.mmgPVBButton.setObjectName(u"mmgPVBButton")
        self.mmgPVBButton.setEnabled(False)
        self.mmgPVBButton.setGeometry(QRect(110, 20, 90, 31))
        self.mmgLevelBox = QComboBox(self.groupBox1)
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.setObjectName(u"mmgLevelBox")
        self.mmgLevelBox.setEnabled(False)
        self.mmgLevelBox.setGeometry(QRect(210, 23, 80, 25))
        self.mmgLevelBox.setDuplicatesEnabled(False)
        self.mmgPVEButton = QPushButton(self.groupBox1)
        self.mmgPVEButton.setObjectName(u"mmgPVEButton")
        self.mmgPVEButton.setEnabled(False)
        self.mmgPVEButton.setGeometry(QRect(300, 20, 90, 31))
        self.mmgBossBox = QComboBox(self.groupBox1)
        self.mmgBossBox.addItem("")
        self.mmgBossBox.addItem("")
        self.mmgBossBox.addItem("")
        self.mmgBossBox.addItem("")
        self.mmgBossBox.setObjectName(u"mmgBossBox")
        self.mmgBossBox.setEnabled(False)
        self.mmgBossBox.setGeometry(QRect(10, 23, 90, 25))
        self.mmgBossBox.setDuplicatesEnabled(False)
        self.groupBox2 = QGroupBox(self.tab1)
        self.groupBox2.setObjectName(u"groupBox2")
        self.groupBox2.setGeometry(QRect(-1, 64, 100, 61))
        self.lamuGrowButton = QPushButton(self.groupBox2)
        self.lamuGrowButton.setObjectName(u"lamuGrowButton")
        self.lamuGrowButton.setEnabled(False)
        self.lamuGrowButton.setGeometry(QRect(10, 20, 80, 31))
        self.groupBox4 = QGroupBox(self.tab1)
        self.groupBox4.setObjectName(u"groupBox4")
        self.groupBox4.setGeometry(QRect(310, 64, 190, 61))
        self.mlcsFightButton = QPushButton(self.groupBox4)
        self.mlcsFightButton.setObjectName(u"mlcsFightButton")
        self.mlcsFightButton.setEnabled(False)
        self.mlcsFightButton.setGeometry(QRect(10, 20, 80, 31))
        self.mlcsSellButton = QPushButton(self.groupBox4)
        self.mlcsSellButton.setObjectName(u"mlcsSellButton")
        self.mlcsSellButton.setEnabled(False)
        self.mlcsSellButton.setGeometry(QRect(100, 20, 80, 31))
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QWidget()
        self.tab2.setObjectName(u"tab2")
        self.groupBox6 = QGroupBox(self.tab2)
        self.groupBox6.setObjectName(u"groupBox6")
        self.groupBox6.setGeometry(QRect(110, 2, 300, 61))
        self.ctSellButton = QPushButton(self.groupBox6)
        self.ctSellButton.setObjectName(u"ctSellButton")
        self.ctSellButton.setEnabled(False)
        self.ctSellButton.setGeometry(QRect(120, 20, 80, 31))
        self.ctDishBox = QComboBox(self.groupBox6)
        self.ctDishBox.setObjectName(u"ctDishBox")
        self.ctDishBox.setEnabled(False)
        self.ctDishBox.setGeometry(QRect(10, 23, 100, 25))
        self.ctDishBox.setDuplicatesEnabled(False)
        self.ctHarvestButton = QPushButton(self.groupBox6)
        self.ctHarvestButton.setObjectName(u"ctHarvestButton")
        self.ctHarvestButton.setEnabled(False)
        self.ctHarvestButton.setGeometry(QRect(210, 20, 80, 31))
        self.groupBox5 = QGroupBox(self.tab2)
        self.groupBox5.setObjectName(u"groupBox5")
        self.groupBox5.setGeometry(QRect(-1, 2, 100, 61))
        self.dddGetButton = QPushButton(self.groupBox5)
        self.dddGetButton.setObjectName(u"dddGetButton")
        self.dddGetButton.setEnabled(False)
        self.dddGetButton.setGeometry(QRect(10, 20, 80, 31))
        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1480, 21))
        self.versionMenu = QMenu(self.menubar)
        self.versionMenu.setObjectName(u"versionMenu")
        self.nodeMenu = QMenu(self.menubar)
        self.nodeMenu.setObjectName(u"nodeMenu")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.versionMenu.menuAction())
        self.menubar.addAction(self.nodeMenu.menuAction())
        self.versionMenu.addAction(self.versionAction1)
        self.versionMenu.addAction(self.versionAction2)
        self.versionMenu.addAction(self.versionAction3)
        self.versionMenu.addAction(self.versionAction4)
        self.versionMenu.addAction(self.versionAction5)
        self.versionMenu.addAction(self.versionAction6)
        self.versionMenu.addAction(self.versionAction7)
        self.nodeMenu.addAction(self.nodeAction1)
        self.nodeMenu.addAction(self.nodeAction2)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u6469\u5c14\u5e84\u56ed", None))
        self.versionAction1.setText(QCoreApplication.translate("MainWindow", u"\u5b98\u670d", None))
        self.versionAction2.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u884c\u670d", None))
        self.versionAction3.setText(QCoreApplication.translate("MainWindow", u"\u9a91\u58eb\u7248", None))
        self.versionAction4.setText(QCoreApplication.translate("MainWindow", u"\u5723\u8bde\u7248", None))
        self.versionAction5.setText(QCoreApplication.translate("MainWindow", u"\u4e07\u5723\u7248", None))
        self.versionAction6.setText(QCoreApplication.translate("MainWindow", u"\u706b\u795e\u7248", None))
        self.versionAction7.setText(QCoreApplication.translate("MainWindow", u"\u6843\u6e90\u7248", None))
        self.nodeAction1.setText(QCoreApplication.translate("MainWindow", u"\u4e3b\u8282\u70b9", None))
        self.nodeAction2.setText(QCoreApplication.translate("MainWindow", u"\u5b50\u8282\u70b9", None))
        self.groupBox.setTitle("")
        self.sendClearButton.setText(QCoreApplication.translate("MainWindow", u"\u6e05\u7a7a", None))
        self.sendLoopButton.setText(QCoreApplication.translate("MainWindow", u"\u5faa\u73af\u53d1\u9001", None))
        self.recvCheckBox.setText(QCoreApplication.translate("MainWindow", u"\u62e6\u622a Recv", None))
        self.sendButton.setText(QCoreApplication.translate("MainWindow", u"\u53d1\u9001", None))
        self.sendCheckBox.setText(QCoreApplication.translate("MainWindow", u"\u62e6\u622a Send", None))
        self.clearButton.setText(QCoreApplication.translate("MainWindow", u"\u6e05\u7a7a\u5c01\u5305", None))
        self.extraButton.setText(QCoreApplication.translate("MainWindow", u"\u62d3\u5c55\u53d1\u9001", None))
        self.groupBox3.setTitle(QCoreApplication.translate("MainWindow", u"\u5143\u7d20\u9a91\u58eb", None))
        self.ysqsFightButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u6311\u6218", None))
        self.ysqsLevelBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u6fc0\u6218\u86cb\u86cb", None))
        self.ysqsLevelBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6c89\u7761\u5965\u4e01", None))
        self.ysqsLevelBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u838e\u58eb\u6469\u4e9a", None))

        self.groupBox1.setTitle(QCoreApplication.translate("MainWindow", u"\u6469\u6469\u602a", None))
        self.mmgPVPButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u6311\u6218\u597d\u53cb", None))
        self.mmgPVBButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u6311\u6218Boss", None))
        self.mmgLevelBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u86ee\u8352\u5c0f\u6797", None))
        self.mmgLevelBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u86ee\u8352\u6df1\u5904", None))
        self.mmgLevelBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u7231\u8428\u6728\u9635", None))
        self.mmgLevelBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\u7231\u8428\u6816\u5730", None))
        self.mmgLevelBox.setItemText(4, QCoreApplication.translate("MainWindow", u"\u6811\u6d1e\u5bc6\u5ba4", None))
        self.mmgLevelBox.setItemText(5, QCoreApplication.translate("MainWindow", u"\u6811\u6d1e\u6df1\u5904", None))
        self.mmgLevelBox.setItemText(6, QCoreApplication.translate("MainWindow", u"\u7075\u5947\u6d1e\u7a74", None))
        self.mmgLevelBox.setItemText(7, QCoreApplication.translate("MainWindow", u"\u7075\u5947\u6811\u6839", None))
        self.mmgLevelBox.setItemText(8, QCoreApplication.translate("MainWindow", u"\u795e\u79d8\u6d1e\u7a74", None))
        self.mmgLevelBox.setItemText(9, QCoreApplication.translate("MainWindow", u"\u78a7\u6c34\u5ca9\u77f3", None))
        self.mmgLevelBox.setItemText(10, QCoreApplication.translate("MainWindow", u"\u6bdb\u5934\u4e4b\u5bb6", None))
        self.mmgLevelBox.setItemText(11, QCoreApplication.translate("MainWindow", u"\u78a7\u6c34\u6d1e", None))
        self.mmgLevelBox.setItemText(12, QCoreApplication.translate("MainWindow", u"\u5e7b\u5f71\u83b2\u6c60", None))
        self.mmgLevelBox.setItemText(13, QCoreApplication.translate("MainWindow", u"\u8424\u706b\u4e4b\u5730", None))
        self.mmgLevelBox.setItemText(14, QCoreApplication.translate("MainWindow", u"\u78a7\u6ce2\u6df1\u5904", None))
        self.mmgLevelBox.setItemText(15, QCoreApplication.translate("MainWindow", u"\u5450\u5947\u6811\u6d1e", None))

        self.mmgPVEButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u6311\u6218\u526f\u672c", None))
        self.mmgBossBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8428\u5c14\u51a5\u738b", None))
        self.mmgBossBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5446\u5446\u725b\u5934\u4eba", None))
        self.mmgBossBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u5730\u72f1\u795e\u72ac", None))
        self.mmgBossBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\u6697\u591c\u7cbe\u7075", None))

        self.groupBox2.setTitle(QCoreApplication.translate("MainWindow", u"\u62c9\u59c6\u53d8\u8eab\u503c", None))
        self.lamuGrowButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u83b7\u53d6", None))
        self.groupBox4.setTitle(QCoreApplication.translate("MainWindow", u"\u9b54\u7075\u4f20\u8bf4", None))
        self.mlcsFightButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u6311\u6218", None))
        self.mlcsSellButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u51fa\u552e", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QCoreApplication.translate("MainWindow", u"\u7b2c1\u9875", None))
        self.groupBox6.setTitle(QCoreApplication.translate("MainWindow", u"\u9910\u5385", None))
        self.ctSellButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u5356\u83dc", None))
        self.ctHarvestButton.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u52a8\u6536\u83dc", None))
        self.groupBox5.setTitle(QCoreApplication.translate("MainWindow", u"\u70b9\u70b9\u8c46", None))
        self.dddGetButton.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u5237\u53d6", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QCoreApplication.translate("MainWindow", u"\u7b2c2\u9875", None))
        self.versionMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u5207\u6362\u7248\u672c", None))
        self.nodeMenu.setTitle(QCoreApplication.translate("MainWindow", u"\u5207\u6362\u8282\u70b9", None))
    # retranslateUi

