# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtAxContainer import QAxWidget
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QHeaderView, QLineEdit, QMainWindow, QMenuBar,
    QPlainTextEdit, QPushButton, QSizePolicy, QTabWidget,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1480, 580)
        MainWindow.setMinimumSize(QSize(1480, 580))
        MainWindow.setMaximumSize(QSize(1480, 580))
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.groupBox = QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(970, 10, 501, 390))
        self.tableWidget = QTableWidget(self.groupBox)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 0, 501, 260))
        self.tableWidget.setMinimumSize(QSize(500, 0))
        self.textEdit = QPlainTextEdit(self.groupBox)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 290, 501, 100))
        self.sendClearButton = QPushButton(self.groupBox)
        self.sendClearButton.setObjectName(u"sendClearButton")
        self.sendClearButton.setGeometry(QRect(446, 360, 50, 25))
        self.sendLoopButton = QPushButton(self.groupBox)
        self.sendLoopButton.setObjectName(u"sendLoopButton")
        self.sendLoopButton.setGeometry(QRect(373, 360, 70, 25))
        self.recvCheckBox = QCheckBox(self.groupBox)
        self.recvCheckBox.setObjectName(u"recvCheckBox")
        self.recvCheckBox.setGeometry(QRect(86, 265, 80, 20))
        self.recvCheckBox.setChecked(True)
        self.sendButton = QPushButton(self.groupBox)
        self.sendButton.setObjectName(u"sendButton")
        self.sendButton.setGeometry(QRect(320, 360, 50, 25))
        self.sendCheckBox = QCheckBox(self.groupBox)
        self.sendCheckBox.setObjectName(u"sendCheckBox")
        self.sendCheckBox.setGeometry(QRect(6, 265, 80, 20))
        self.sendCheckBox.setChecked(True)
        self.clearButton = QPushButton(self.groupBox)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setGeometry(QRect(162, 262, 61, 26))
        self.socketLineEdit = QLineEdit(self.groupBox)
        self.socketLineEdit.setObjectName(u"socketLineEdit")
        self.socketLineEdit.setEnabled(False)
        self.socketLineEdit.setGeometry(QRect(450, 265, 50, 20))
        self.socketCheckBox = QCheckBox(self.groupBox)
        self.socketCheckBox.setObjectName(u"socketCheckBox")
        self.socketCheckBox.setGeometry(QRect(360, 265, 85, 20))
        self.axWidget = QAxWidget(self.centralWidget)
        self.axWidget.setControl(u"{d27cdb6e-ae6d-11cf-96b8-444553540000}")
        self.axWidget.setObjectName(u"axWidget")
        self.axWidget.setProperty(u"geometry", QRect(0, 0, 960, 560))
        self.tabWidget = QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(970, 402, 500, 148))
        self.tabWidget.setStyleSheet(u"QTabWidget::pane {\n"
"    background-color: #F0F0F0;\n"
"	border: 1px solid #DCDCDC;\n"
"}")
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.groupBox2 = QGroupBox(self.tab1)
        self.groupBox2.setObjectName(u"groupBox2")
        self.groupBox2.setGeometry(QRect(-1, 64, 500, 61))
        self.ysqsFightButton = QPushButton(self.groupBox2)
        self.ysqsFightButton.setObjectName(u"ysqsFightButton")
        self.ysqsFightButton.setEnabled(False)
        self.ysqsFightButton.setGeometry(QRect(109, 20, 86, 31))
        self.ysqsLevelBox = QComboBox(self.groupBox2)
        self.ysqsLevelBox.addItem("")
        self.ysqsLevelBox.addItem("")
        self.ysqsLevelBox.addItem("")
        self.ysqsLevelBox.addItem("")
        self.ysqsLevelBox.setObjectName(u"ysqsLevelBox")
        self.ysqsLevelBox.setEnabled(False)
        self.ysqsLevelBox.setGeometry(QRect(10, 23, 90, 25))
        self.ysqsLevelBox.setDuplicatesEnabled(False)
        self.ysqsCardBox = QComboBox(self.groupBox2)
        self.ysqsCardBox.setObjectName(u"ysqsCardBox")
        self.ysqsCardBox.setEnabled(False)
        self.ysqsCardBox.setGeometry(QRect(204, 23, 110, 25))
        self.ysqsCardBox.setDuplicatesEnabled(False)
        self.ysqsUpgradeButton = QPushButton(self.groupBox2)
        self.ysqsUpgradeButton.setObjectName(u"ysqsUpgradeButton")
        self.ysqsUpgradeButton.setEnabled(False)
        self.ysqsUpgradeButton.setGeometry(QRect(322, 20, 80, 31))
        self.ysqsAdvanceButton = QPushButton(self.groupBox2)
        self.ysqsAdvanceButton.setObjectName(u"ysqsAdvanceButton")
        self.ysqsAdvanceButton.setEnabled(False)
        self.ysqsAdvanceButton.setGeometry(QRect(410, 20, 80, 31))
        self.groupBox1 = QGroupBox(self.tab1)
        self.groupBox1.setObjectName(u"groupBox1")
        self.groupBox1.setGeometry(QRect(-1, 2, 500, 61))
        self.mmgPVPButton = QPushButton(self.groupBox1)
        self.mmgPVPButton.setObjectName(u"mmgPVPButton")
        self.mmgPVPButton.setEnabled(False)
        self.mmgPVPButton.setGeometry(QRect(403, 20, 89, 31))
        self.mmgPVBButton = QPushButton(self.groupBox1)
        self.mmgPVBButton.setObjectName(u"mmgPVBButton")
        self.mmgPVBButton.setEnabled(False)
        self.mmgPVBButton.setGeometry(QRect(107, 20, 89, 31))
        self.mmgLevelBox = QComboBox(self.groupBox1)
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.addItem("")
        self.mmgLevelBox.setObjectName(u"mmgLevelBox")
        self.mmgLevelBox.setEnabled(False)
        self.mmgLevelBox.setGeometry(QRect(203, 23, 98, 25))
        self.mmgLevelBox.setDuplicatesEnabled(False)
        self.mmgPVEButton = QPushButton(self.groupBox1)
        self.mmgPVEButton.setObjectName(u"mmgPVEButton")
        self.mmgPVEButton.setEnabled(False)
        self.mmgPVEButton.setGeometry(QRect(308, 20, 89, 31))
        self.mmgBossBox = QComboBox(self.groupBox1)
        self.mmgBossBox.addItem("")
        self.mmgBossBox.addItem("")
        self.mmgBossBox.addItem("")
        self.mmgBossBox.addItem("")
        self.mmgBossBox.addItem("")
        self.mmgBossBox.setObjectName(u"mmgBossBox")
        self.mmgBossBox.setEnabled(False)
        self.mmgBossBox.setGeometry(QRect(10, 23, 90, 25))
        self.mmgBossBox.setDuplicatesEnabled(False)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QWidget()
        self.tab2.setObjectName(u"tab2")
        self.groupBox4 = QGroupBox(self.tab2)
        self.groupBox4.setObjectName(u"groupBox4")
        self.groupBox4.setGeometry(QRect(199, 2, 300, 61))
        self.ctSellButton = QPushButton(self.groupBox4)
        self.ctSellButton.setObjectName(u"ctSellButton")
        self.ctSellButton.setEnabled(False)
        self.ctSellButton.setGeometry(QRect(120, 20, 80, 31))
        self.ctDishBox = QComboBox(self.groupBox4)
        self.ctDishBox.setObjectName(u"ctDishBox")
        self.ctDishBox.setEnabled(False)
        self.ctDishBox.setGeometry(QRect(10, 23, 100, 25))
        self.ctDishBox.setDuplicatesEnabled(False)
        self.ctHarvestButton = QPushButton(self.groupBox4)
        self.ctHarvestButton.setObjectName(u"ctHarvestButton")
        self.ctHarvestButton.setEnabled(False)
        self.ctHarvestButton.setGeometry(QRect(210, 20, 80, 31))
        self.groupBox6 = QGroupBox(self.tab2)
        self.groupBox6.setObjectName(u"groupBox6")
        self.groupBox6.setGeometry(QRect(98, 64, 100, 61))
        self.dddGetButton = QPushButton(self.groupBox6)
        self.dddGetButton.setObjectName(u"dddGetButton")
        self.dddGetButton.setEnabled(False)
        self.dddGetButton.setGeometry(QRect(10, 20, 80, 31))
        self.groupBox8 = QGroupBox(self.tab2)
        self.groupBox8.setObjectName(u"groupBox8")
        self.groupBox8.setGeometry(QRect(296, 64, 102, 61))
        self.bhOpenButton = QPushButton(self.groupBox8)
        self.bhOpenButton.setObjectName(u"bhOpenButton")
        self.bhOpenButton.setEnabled(False)
        self.bhOpenButton.setGeometry(QRect(11, 20, 80, 31))
        self.groupBox3 = QGroupBox(self.tab2)
        self.groupBox3.setObjectName(u"groupBox3")
        self.groupBox3.setGeometry(QRect(-1, 2, 201, 61))
        self.mlcsFightButton = QPushButton(self.groupBox3)
        self.mlcsFightButton.setObjectName(u"mlcsFightButton")
        self.mlcsFightButton.setEnabled(False)
        self.mlcsFightButton.setGeometry(QRect(10, 20, 86, 31))
        self.mlcsSellButton = QPushButton(self.groupBox3)
        self.mlcsSellButton.setObjectName(u"mlcsSellButton")
        self.mlcsSellButton.setEnabled(False)
        self.mlcsSellButton.setGeometry(QRect(105, 20, 86, 31))
        self.groupBox5 = QGroupBox(self.tab2)
        self.groupBox5.setObjectName(u"groupBox5")
        self.groupBox5.setGeometry(QRect(-1, 64, 100, 61))
        self.lamuGrowButton = QPushButton(self.groupBox5)
        self.lamuGrowButton.setObjectName(u"lamuGrowButton")
        self.lamuGrowButton.setEnabled(False)
        self.lamuGrowButton.setGeometry(QRect(10, 20, 80, 31))
        self.groupBox7 = QGroupBox(self.tab2)
        self.groupBox7.setObjectName(u"groupBox7")
        self.groupBox7.setGeometry(QRect(197, 64, 100, 61))
        self.medGetButton = QPushButton(self.groupBox7)
        self.medGetButton.setObjectName(u"medGetButton")
        self.medGetButton.setEnabled(False)
        self.medGetButton.setGeometry(QRect(10, 20, 80, 31))
        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1480, 21))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.mmgLevelBox.setCurrentIndex(27)
        self.mmgBossBox.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"摩尔庄园", None))
        self.groupBox.setTitle("")
        self.sendClearButton.setText(QCoreApplication.translate("MainWindow", u"清空", None))
        self.sendLoopButton.setText(QCoreApplication.translate("MainWindow", u"循环发送", None))
        self.recvCheckBox.setText(QCoreApplication.translate("MainWindow", u"拦截 Recv", None))
        self.sendButton.setText(QCoreApplication.translate("MainWindow", u"发送", None))
        self.sendCheckBox.setText(QCoreApplication.translate("MainWindow", u"拦截 Send", None))
        self.clearButton.setText(QCoreApplication.translate("MainWindow", u"清空封包", None))
        self.socketLineEdit.setText("")
        self.socketCheckBox.setText(QCoreApplication.translate("MainWindow", u"指定通信号：", None))
        self.groupBox2.setTitle(QCoreApplication.translate("MainWindow", u"元素骑士", None))
        self.ysqsFightButton.setText(QCoreApplication.translate("MainWindow", u"一键挑战", None))
        self.ysqsLevelBox.setItemText(0, QCoreApplication.translate("MainWindow", u"中秋探险", None))
        self.ysqsLevelBox.setItemText(1, QCoreApplication.translate("MainWindow", u"挑战汉青", None))
        self.ysqsLevelBox.setItemText(2, QCoreApplication.translate("MainWindow", u"激战蛋蛋", None))
        self.ysqsLevelBox.setItemText(3, QCoreApplication.translate("MainWindow", u"沉睡的奥丁", None))

        self.ysqsUpgradeButton.setText(QCoreApplication.translate("MainWindow", u"一键升级", None))
        self.ysqsAdvanceButton.setText(QCoreApplication.translate("MainWindow", u"进阶", None))
        self.groupBox1.setTitle(QCoreApplication.translate("MainWindow", u"摩摩怪", None))
        self.mmgPVPButton.setText(QCoreApplication.translate("MainWindow", u"一键挑战好友", None))
        self.mmgPVBButton.setText(QCoreApplication.translate("MainWindow", u"一键挑战Boss", None))
        self.mmgLevelBox.setItemText(0, QCoreApplication.translate("MainWindow", u"蛮荒小林", None))
        self.mmgLevelBox.setItemText(1, QCoreApplication.translate("MainWindow", u"蛮荒深处", None))
        self.mmgLevelBox.setItemText(2, QCoreApplication.translate("MainWindow", u"爱萨木阵", None))
        self.mmgLevelBox.setItemText(3, QCoreApplication.translate("MainWindow", u"爱萨栖地", None))
        self.mmgLevelBox.setItemText(4, QCoreApplication.translate("MainWindow", u"蛮荒小林疯狂", None))
        self.mmgLevelBox.setItemText(5, QCoreApplication.translate("MainWindow", u"蛮荒深处疯狂", None))
        self.mmgLevelBox.setItemText(6, QCoreApplication.translate("MainWindow", u"爱萨木阵疯狂", None))
        self.mmgLevelBox.setItemText(7, QCoreApplication.translate("MainWindow", u"爱萨栖地疯狂", None))
        self.mmgLevelBox.setItemText(8, QCoreApplication.translate("MainWindow", u"树洞密室", None))
        self.mmgLevelBox.setItemText(9, QCoreApplication.translate("MainWindow", u"树洞深处", None))
        self.mmgLevelBox.setItemText(10, QCoreApplication.translate("MainWindow", u"灵奇洞穴", None))
        self.mmgLevelBox.setItemText(11, QCoreApplication.translate("MainWindow", u"灵奇树根", None))
        self.mmgLevelBox.setItemText(12, QCoreApplication.translate("MainWindow", u"树洞密室疯狂", None))
        self.mmgLevelBox.setItemText(13, QCoreApplication.translate("MainWindow", u"树洞深处疯狂", None))
        self.mmgLevelBox.setItemText(14, QCoreApplication.translate("MainWindow", u"灵奇洞穴疯狂", None))
        self.mmgLevelBox.setItemText(15, QCoreApplication.translate("MainWindow", u"灵奇树根疯狂", None))
        self.mmgLevelBox.setItemText(16, QCoreApplication.translate("MainWindow", u"神秘洞穴", None))
        self.mmgLevelBox.setItemText(17, QCoreApplication.translate("MainWindow", u"碧水岩石", None))
        self.mmgLevelBox.setItemText(18, QCoreApplication.translate("MainWindow", u"毛头之家", None))
        self.mmgLevelBox.setItemText(19, QCoreApplication.translate("MainWindow", u"碧水洞", None))
        self.mmgLevelBox.setItemText(20, QCoreApplication.translate("MainWindow", u"神秘洞穴疯狂", None))
        self.mmgLevelBox.setItemText(21, QCoreApplication.translate("MainWindow", u"碧水岩石疯狂", None))
        self.mmgLevelBox.setItemText(22, QCoreApplication.translate("MainWindow", u"毛头之家疯狂", None))
        self.mmgLevelBox.setItemText(23, QCoreApplication.translate("MainWindow", u"碧水洞疯疯狂", None))
        self.mmgLevelBox.setItemText(24, QCoreApplication.translate("MainWindow", u"幻影莲池", None))
        self.mmgLevelBox.setItemText(25, QCoreApplication.translate("MainWindow", u"萤火之地", None))
        self.mmgLevelBox.setItemText(26, QCoreApplication.translate("MainWindow", u"碧波深处", None))
        self.mmgLevelBox.setItemText(27, QCoreApplication.translate("MainWindow", u"呐奇树洞", None))
        self.mmgLevelBox.setItemText(28, QCoreApplication.translate("MainWindow", u"幻影莲池疯狂", None))
        self.mmgLevelBox.setItemText(29, QCoreApplication.translate("MainWindow", u"萤火之地疯狂", None))
        self.mmgLevelBox.setItemText(30, QCoreApplication.translate("MainWindow", u"碧波深处疯狂", None))
        self.mmgLevelBox.setItemText(31, QCoreApplication.translate("MainWindow", u"呐奇树洞疯狂", None))

        self.mmgPVEButton.setText(QCoreApplication.translate("MainWindow", u"一键挑战副本", None))
        self.mmgBossBox.setItemText(0, QCoreApplication.translate("MainWindow", u"呆呆牛头人", None))
        self.mmgBossBox.setItemText(1, QCoreApplication.translate("MainWindow", u"地狱神犬", None))
        self.mmgBossBox.setItemText(2, QCoreApplication.translate("MainWindow", u"暗夜精灵", None))
        self.mmgBossBox.setItemText(3, QCoreApplication.translate("MainWindow", u"萨尔冥王", None))
        self.mmgBossBox.setItemText(4, QCoreApplication.translate("MainWindow", u"独角萨摩", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QCoreApplication.translate("MainWindow", u"第1页", None))
        self.groupBox4.setTitle(QCoreApplication.translate("MainWindow", u"餐厅", None))
        self.ctSellButton.setText(QCoreApplication.translate("MainWindow", u"一键卖菜", None))
        self.ctHarvestButton.setText(QCoreApplication.translate("MainWindow", u"自动做菜", None))
        self.groupBox6.setTitle(QCoreApplication.translate("MainWindow", u"点点豆", None))
        self.dddGetButton.setText(QCoreApplication.translate("MainWindow", u"一键刷取", None))
        self.groupBox8.setTitle(QCoreApplication.translate("MainWindow", u"缤纷七彩宝盒", None))
        self.bhOpenButton.setText(QCoreApplication.translate("MainWindow", u"一键开启", None))
        self.groupBox3.setTitle(QCoreApplication.translate("MainWindow", u"魔灵传说", None))
        self.mlcsFightButton.setText(QCoreApplication.translate("MainWindow", u"一键挑战", None))
        self.mlcsSellButton.setText(QCoreApplication.translate("MainWindow", u"一键出售", None))
        self.groupBox5.setTitle(QCoreApplication.translate("MainWindow", u"拉姆变身值", None))
        self.lamuGrowButton.setText(QCoreApplication.translate("MainWindow", u"一键获取", None))
        self.groupBox7.setTitle(QCoreApplication.translate("MainWindow", u"摩尔豆", None))
        self.medGetButton.setText(QCoreApplication.translate("MainWindow", u"一键刷取", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QCoreApplication.translate("MainWindow", u"第2页", None))
    # retranslateUi

