name: 打包

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5
      - name: 安装环境
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - name: 设置环境
        shell: python
        run: |
          from datetime import datetime
          from hashlib import md5
          from os import environ
          from tomllib import load
          with open("pyproject.toml", "rb") as file:
              project = load(file)["project"]
          with open("deps.hash", "w") as file:
              file.write(md5(str(sorted(project["dependencies"])).encode()).hexdigest())
          with open(environ["GITHUB_ENV"], "a", encoding="utf-8") as env:
              env.write(f"VERSION={project["version"]}\n")
              env.write(f"DESCRIPTION<<EOF\n{project["description"].strip()}\nEOF\n")
              env.write(f"NUITKA_PATH={environ["localappdata"]}\\Nuitka\\Nuitka\\Cache\n")
              env.write(f"WEEK={datetime.now().strftime("%V")}\n")
      - name: 查询标签
        id: check
        uses: action-pack/tag-exists@v1
        with:
          tag: v${{ env.VERSION }}
      - name: 安装环境
        if: steps.check.outputs.exists == 'false'
        uses: astral-sh/setup-uv@v8.2.0
        with:
          cache-dependency-glob: deps.hash
          prune-cache: false
      - name: 安装依赖
        if: steps.check.outputs.exists == 'false'
        run: |
          uv sync
      - name: 编译缓存
        if: steps.check.outputs.exists == 'false'
        uses: actions/cache@v4
        with:
          path: ${{ env.NUITKA_PATH }}
          key: nuitka-${{ env.WEEK }}
          restore-keys: nuitka-
      - name: 开始编译
        if: steps.check.outputs.exists == 'false'
        run: |
          uv run build.py
      - name: 上传文件
        if: steps.check.outputs.exists == 'false'
        uses: actions/upload-artifact@v5
        with:
          name: mole
          path: D:/Downloads/*.exe
      - name: 复查标签
        if: steps.check.outputs.exists == 'false'
        id: recheck
        uses: action-pack/tag-exists@v1
        with:
          tag: v${{ env.VERSION }}
      - name: 创建标签
        if: steps.recheck.outputs.exists == 'false'
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
      - name: 发布版本
        if: steps.check.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.VERSION }}
          body: ${{ env.DESCRIPTION }}
          tag_name: v${{ env.VERSION }}
          files: D:/Downloads/*.exe